---
- name: Add mssql tools repository
  yum_repository:
    name: packages-microsoft-com-prod 
    description: packages-microsoft-com-prod
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
  notify: yum-clean-metadata

- name: Install expect
  yum: name=expect

- name: Initial setup of sql server
  shell: expect -c 'spawn /usr/bin/yum -y install mssql-tools; expect "Do you accept the license terms? (Enter YES or NO)"; send "YES\n"; expect completed; interact'
  ignore_errors: true
  register: res


- name: add path to sqlcmd
  lineinfile:
    path: /home/vagrant/.bash_profile
    line: PATH=$PATH:/opt/mssql-tools/bin
    insertbefore: '^export\ PATH'
    state: present
